DROP TABLE IF EXISTS APP_USER;

CREATE TABLE APP_USER (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
USER_NAME VARCHAR(200) NOT NULL,
PASSWORD VARCHAR(200) NOT NULL,
STATUS VARCHAR(1) NOT NULL,
CREATED_DATE TIMESTAMP WITH TIME ZONE,
MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

