spring:
  config:
    import:
    - classpath:common.yml
---
server:
  port: ${EMPLOYEE_SERVICE_PORT:(@authorization.service.port@)}
  forward-headers-strategy: framework

spring:
  r2dbc:
    url: ${DB_URL:(@authorization.db.url@)}
    username: ${DB_USERNAME:(@authorization.db.username@)}
    password: ${DB_PASSWORD:(@authorization.db.password@)}
  datasource:
    platform: ${DB_PLATFORM:(@authorization.db.platform@)}