spring:
  config:
    import:
    - classpath:common.yml
---
# HTTP (Tomcat) port
server:
  port: ${BOOKING_SERVICE_PORT:(@booking.service.port@)}
  forward-headers-strategy: framework

spring:
  r2dbc:
    url: ${DB_URL:(@booking.db.url@)}
    username: ${DB_USERNAME:(@booking.db.username@)}
    password: ${DB_PASSWORD:(@booking.db.password@)}
  datasource:
    platform: ${DB_PLATFORM:(@booking.db.platform@)}