spring:
  config:
    import:
    - classpath:common.yml
---
# HTTP (Tomcat) port
server:
  port: ${EMPLOYEE_SERVICE_PORT:(@employee.service.port@)}
  forward-headers-strategy: framework

spring:
  datasource:
    platform: ${DB_PLATFORM:(@employee.db.platform@)}
    url: ${DB_URL:(@employee.db.url@)}
    username: ${DB_USERNAME:(@employee.db.username@)}
    password: ${DB_PASSWORD:(@employee.db.password@)}
    driverClassName: ${DB_DRIVER:(@employee.db.driver@)}
    validationQuery: SELECT 1