DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(200) NOT NULL,
STATUS VARCHAR(1) NOT NULL,
CREATED_DATE TIMESTAMP WITH TIME ZONE,
MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

